[project]
name = "esobuilder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "bs4>=0.0.2",
    "chromadb>=1.0.20",
    "ipykernel>=6.30.1",
]
